### ISSUE TITLE
FEATURE REQUEST - Automate Update of Mirrors etc...

### ISSUE THREAD

**Issue by jshand2015** [manjaro/pamac#153]
Pamac is a great application.  i have recently switched from octopi.

However, i have noticed that when a month or more has passed, there is no automation for the updating of pacman-mirrors or a forced update of the repositories and what happens a lot is that you stop receiving updates after a while as the mirrors become out of date and then so does the repos.

1.  Have an option within pamac to enable automation of pacman-mirrors.  this might need to be a cron job.  this would be a forced update.
2.  Always force the refresh of all your repos after mirrors have been updated.
3.  Also add a function to detect whether you have a SSD or a HDD drive.  Once that has been determined then run the pacman-optimise && sync command.  this would also be forced.  however, if a SSD is detected this command 'pacman-optimise && sync' will not be performed

This should stop any further problems where people don't seem to get updates correctly.

**Comment by Photon89** [comment]
I think, this needs to solve two problems: 
1. offline mirrors
2. out of date mirrors
Maybe http://repo.manjaro.org/repository-state can be parsed in order to recognize whether the current mirror is up to date?

**Comment by guinux** [comment]
Hi all,
I'm the developer of pamac,
what would you think about adding a systemd timer unit to monthly run "pacman-mirrors -g" in pamac?

**Comment by jshand2015** [comment]
yeah that would work.  however we could be left with another issue.  does pacman-mirrors -g actually find new mirrors and remove dead links??

**Comment by guinux** [comment]
When there are new mirrors and/or offline ones, we have an update of the package pacman-mirrorlist which auto run pacman-mirrors -g after the update.
If a mirror doesn't respond it also don't add it in the list.
This automation would permit to always have the best list as possible.

**Comment by tele1** [comment]
Thanks for info about this topic.  :simple_smile:

1. 

> what would you think about adding a systemd timer unit to monthly run "pacman-mirrors -g" in pamac?

It can be, but
* once a month - it does not make sense, repository may be break at any time.
And this not not solve error
_**" can not download core.db , extra.db it is not obvious. "**_
I guess it is from pacman, so maybe exist  way to parse this error
 and create window with error and suggestion to change repository ?

* run  "pacman-mirrors -g"  every time -  it also does not make sense,
 because most peple use only part repositories from list. 

* I think "pacman-mirrors -g" should be when we want edit or change list active (on/off) repositories.

* What will if I used before old repository and now not exist in new list ? I will question which repository use or it will set by default ?

**Comment by guinux** [comment]
Note that if you have several mirrors in your mirrorlist, alpm (pacman library use by pamac) will auto try next mirror if a download failed.
If your mirror is no more on the new list, pacman-mirrors -g will remove it.

**Comment by tele1** [comment]
So I am for
1.  **"pacman-mirrors -g"** should be when we want edit or change list active (on/off) repositories.
2.  And if you can run **"pacman-mirrors -g"** and add **sensible information**  when pamac will have error about repository, it will be great.

Other way can be once a month **"pacman-mirrors -g"** like fuse,
but it is not good way.

**Comment by guinux** [comment]
To create you own repo list you can create it with the "Custom" country name.

**Comment by guinux** [comment]
see 74d1902
