### ISSUE TITLE
pt-br translation is not 100% visible in updates notification on KDE Plasma 5

### ISSUE THREAD

**Issue by glaubersm** [manjaro/pamac#156]
"Exibir atualizações" is cut off. See the screenshot please.
http://imgbox.com/r3rLzZPF

**Comment by guinux** [comment]
I think it's more a plasma notifier problem than a pamac one.

**Comment by glaubersm** [comment]
Are you sure? I reported this in KDE bugzilla some days ago
https://bugs.kde.org/show_bug.cgi?id=367617
Reading comments seems this is not a kde issue.

**Comment by scachemaille** [comment]
I'm not sure it's a "bug" anywhere. I don't know pamac can say to the notifier to redimension the string or to wrap it. and by default it truncate the string

**Comment by glaubersm** [comment]
translation not 100% visible is a bug.  Where is this bug? I dont know. I am not a software developer.
I am doing my part reporting this and I hope any fix.

**Comment by philmmanjaro** [comment]
Is there no shorter word for it?

**Comment by glaubersm** [comment]
I think maybe "Exibir..." ("show") is enough. Because this notification is about updates, therefore when the user read "Exibir..." implicitly user knows that the available updates will be displayed on screen when the button is clicked.. Or "Ver atualizações" ("ver" means "see")

**Comment by guinux** [comment]
Yes it's an idea, maybe also "Details" which is already translated

**Comment by scachemaille** [comment]
as I supposed. there is no possibility in the notification api to change the "design" of the notification of the DE. and plasma limit the size of the action button. (good thing otherwise it could have some ugly notifications ;)). maybe the limit is a little too small but I don't think the kde devs will change it.
here the snipet of the qml code of the plasma notification for the action button.
_**/usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationItem.qml**_

       ColumnLayout {
                id: actionsColumn
                Layout.alignment: Qt.AlignTop
                Layout.maximumWidth: theme.mSize(theme.defaultFont).width * (compact ? 8 : 12)

                spacing: units.smallSpacing
                visible: notificationItem.actions && notificationItem.actions.count > 0

                Repeater {
                    id: actionRepeater
                    model: notificationItem.actions

                    PlasmaComponents.Button {
                        Layout.maximumWidth: actionsColumn.Layout.maximumWidth
                        text: model.text
                        onClicked: notificationItem.action(model.id)
                    }
                }
            }
the width limit is:
`Layout.maximumWidth: theme.mSize(theme.defaultFont).width * (compact ? 8 : 12)`

There is different solutions:
- Ask KDE dev to change that but it can appear again for other longer text. There is no ideal design solution, and I doubt they will do it.
- Find an other translation that fit the button width
- To accept the truncated translation. it's the purpose of the "..." to tell that the text is to long.

**Comment by guinux** [comment]
done in a405052
