### ISSUE TITLE
pamac 4.1.3 failing to load libappindicator3.so.1

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pamac#163]
```
pamac-tray: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory
```

**Comment by FredBezies** [comment]
Libappindicator is now a depend of pamac. I had to build it on my archlinux - with libindicator-gtk3 and libdbusmenu-gtk3 in order to have last pamac...

What a pain in the bottom... I thought octopi was the GUI for pacman and KDE under Manjaro. I was wrong. Just look at this commit : https://github.com/manjaro/pamac/commit/d840b05e915335a300cede02dcaa3648be764fa1

**Comment by oberon2007** [comment]
Hm. But I am getting this error in i3 :wink:
``use_indicator = Environment.get_variable ("XDG_CURRENT_DESKTOP") == "KDE";``
```
$ echo $XDG_CURRENT_DESKTOP
i3
```

**Comment by FredBezies** [comment]
Same for me, but I'm using Mate Desktop : 

```
[fred@fredo-arch ~]$ echo $XDG_CURRENT_DESKTOP
MATE
```

This commit is the **worst** idea for Mate, Gnome, Xfce or any wm user...

**Comment by lots0logs** [comment]
This was my original concern with the way that support for `libappindicator` was recently implemented. Even as a make dependency, it is a huge PIA for those who its not even going to benefit (non KDE users). Maybe [my work-around](https://github.com/manjaro/pamac/pull/161) was not so crazy afterall?

**Comment by philmmanjaro** [comment]
For **pamac 4.1.3-2** I've reverted d840b05. **pamac-dev** I've updated to lastest git-snapshot.

**Comment by oberon2007** [comment]
Thank you. Works as expected. :)

**Comment by FredBezies** [comment]
Work for me too. Thanks.
