### ISSUE TITLE
ability to copy pamac output in to the buffer

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#175]
I'm having trouble installing a specific package and when I go to hightlight the error i have no way to copy it in to the buffer. Using a 2 finger tap on the trackpad doesn't trigger a menu. If I use Ctrl+c or Shift+Ctrl+c then I abort the current pamac operation. Pamac has no drop down menu for me to use. Please advise (besides using pacman). Thanks!

**Comment by MachmanFive** [comment]
Don't ctrl+insert(copy) and shift+insert(paste) work?

**Comment by luzpaz** [comment]
Interesting. That worked. 
@MachmanFive that is the first time I've encountered using those key-combos before.

**Comment by luzpaz** [comment]
> Don't ctrl+insert(copy) and shift+insert(paste) work?

I don't think this is explicit enough for users to use

**Comment by MachmanFive** [comment]
>I don't think this is explicit enough for users to use
Indeed, it's an arcane keybind from IBM systems that I only happen to know because I spend way too much time on wikipedia.
To be completely honest the whole clipboard mechanics and keybindings on linux are so convoluted(you could, I think, also  "copy" by just selecting and "paste" with your middle mouse button) that adding a right click menu with a copy option might be warranted.

**Comment by luzpaz** [comment]
Related to #137

**Comment by guinux** [comment]
Fixed in v4.2.9, use ctrl+ or right click on the terminal window.
