### ISSUE TITLE
pamac behind proxy?

### ISSUE THREAD

**Issue by ericho** [manjaro/pamac#2]
Hi, It is possible to use pamac behind a proxy? 
If I start pamac-updater the application is unable to reach the servers. 
pacman works ok with the general environment http_proxy but pamac does not. 

I tried to dig in the code but i'm not sure where to start. 

Thanks.

**Comment by snachx** [comment]
Same problem here, the latest version of pamac doesn't work behind a proxy.

I tried all kinds of methods:
1. set the http_proxy and https_proxy in /etc/environment
2. set .bashrc for both root user and current user.
3. use gsettings to set gnome proxy

None of those works. Could you please help to solve this problem?

**Comment by lestcape** [comment]
As i say, the solution is in the link that i provide. Apparently no one take a look of this... Let me explain, what is there, is a code that can extract the proxy setting from gnome and create a dictionary with all properties from the connection (the proxy). This NOT need an special python library, is only the mechanism and the mechanism can be  ported easy to vala...

**Comment by snachx** [comment]
@manjaro 
https://developer.gnome.org/ProxyConfiguration/
Gnome Project officially recommends using  GProxyResolver API. And the solution adopted by cinnamon which using gsettings as @lestcape mentioned also works. I don't know vala and I have no time to read the source code deeply, is there someone helps solving this?

**Comment by philmmanjaro** [comment]
We are always glad for suggestions. When Guillaume will find time, he'll take a look at it.

**Comment by guinux** [comment]
I know the problem. There is the same issue with pacman and pamac. It's the fault of libalpm download function which use a unconfigurable timeout of 10s.
You can configure pacman to use a custom download command but it's not yet supported by pamac:
https://wiki.archlinux.org/index.php/Improve_pacman_performance#Using_wget

**Comment by lestcape** [comment]
@guinux hey, manjaro have not a different pacmac implementation? I need to patch how handled the  libalpm signals, because they are handled different in manjaro and in arch... https://github.com/lestcape/Cinnamon-Installer/blob/master/installer_modules/ci_pac.py#L480 I really don't use manjaro or arch, this not affect me at all.

**Comment by snachx** [comment]
@guinux 
My problem is different from @ericho , it is not connection timeout error but resolve host error.
What you said is not the reason of my problem. In my environment, pacman has no problem when http_proxy and https_proxy are correctly set. 
I checked the proxy's log and there's no output when using pamac, it means that there's no requests started through the proxy, but when I use pacman, everything is OK.
I also tried to configure pacman to use wget, pamac still doesn't work.

Error: failed retrieving file 'core.db' from lug.mit.edu : Could not resolve host: lug.mit.edu
Error: failed retrieving file 'core.db' from mirror.jmu.edu : Could not resolve host: mirror.jmu.edu
Error: failed retrieving file 'core.db' from mirror.dacentec.com : Could not resolve host: mirror.dacentec.com

**Comment by guinux** [comment]
@lestcape: libalpm signals are the same in manjaro and arch. What do you want to do?
@snachx: ok, I will investigate when I have time.

**Comment by lestcape** [comment]
@guinux thats is an old history. As cinnamon can run on differents architectures with different packages format, packages managers, packages names, and libraries. Is problematic decide on time, how to install a package. In some extensions (applets, desklets...) will required dependencies to hard (normal) packages. Currently, the way to resolve this problematic, is alert the user that he need to install this packages, but i think is possible make this automatically, if the devs provide the dependencies for his extensions in concordance to the distro where the extension can be installed. Then we can perform an instalation automatically if some one provide a "backend", for the system libraries, in the manjaro case the backend that i use for libalpm is the pamac python implementation that i convert on a plugin to my application.

As the first approximation, i only take on account make a tool for install one package, but now i want to be more general and use this in the problematic of the cinnamon extensions. The model that i have is more or less similar to packages-kit, where is needed a backend for my program. This is working well on manjaro, but i tested it on arch and for some reason, the libalpm signals have differents parameters, so i checked the parameters and reorganised then, according of how i want to use it . I think is because manjaro have a fork of libalpm or a fork of the python bindings at less. I don't know because i resolve the problem in that way i don't take a deep look to this. Now you say that is a fault of libalpm, and i interpret of this that you are using the arch libalpm implementation. This then was interesting for me, as I had a different idea, no more.

**Comment by guinux** [comment]
No you were right, now I remember that manjaro uses a patched version of
pyalpm.

Le 3 juil. 2015 21:09, "Lester Carballo Pérez" <notifications@github.com> a
écrit :
>
> @guinux thats is an old history. As cinnamon can run on differents
architectures with different packages format, packages managers, packages
names, and libraries. Is problematic decide on time, how to install a
package. In some extensions (applets, desklets...) will required
dependencies to hard (normal) packages. Currently, the way to resolve this
problematic, is alert the user that he need to install this packages, but i
think is possible make this automatically, if the devs provide the
dependencies for his extensions in concordance to the distro where the
extension can be installed. Then we can perform an instalation
automatically if some one provide a "backend", for the system libraries, in
the manjaro case the backend that i use for libalpm is the pamac python
implementation that i convert on a plugin to my application.
>
> As the first approximation, i only take on account make a tool for
install one package, but now i want to be more general and use this in the
problematic of the cinnamon extensions. The model that i have is more or
less similar to packages-kit, where is needed a backend for my program.
This is working well on manjaro, but i tested it on arch and for some
reason, the libalpm signals have differents parameters, so i checked the
parameters and reorganised then, according of how i want to use it . I
think is because manjaro have a fork of libalpm or a fork of the python
bindings at less. I don't know because i resolve the problem in that way i
don't take a deep look to this. Now you say that is a fault of libalpm, and
i interpret of this that you are using the arch libalpm implementation.
This then was interesting for me, as I had a different idea, no more.

**Comment by philmmanjaro** [comment]
Well, we are still using the **SyncFirst** option for **manjaro-system**. That is why we have a patch for our **pacman**.

**Comment by lestcape** [comment]
@philmmanjaro  Yes, only a comment about this. I suppose was better put the new parameters at the end, not override any other parameter, and check if the new parameters exist inside the function. In this way, we can continue with the old compatibility and add new behaviours without affecting the old one in an easy way. I don't recommend change it again to this way, just to be take in account for new patches...

**Comment by philmmanjaro** [comment]
@lestcape: I assume you're talking about [this patch](https://github.com/manjaro/packages-core/blob/master/pacman/pacman-sync-first-option.patch). If you have a better way to solve this issue, I'm open for it. @guinux created that patch for us. Any solution is appreciated. Having the option to use **pamac** behind a proxy would be nice to have ...

**Comment by lestcape** [comment]
@philmmanjaro  as i can see, in this patch there are not any problematic things, i was talking about other thing... i.e. this patch not affected the external face of libalpm or the bindings, this is the only thing that need to be taking on account (try to not affect the library interface). This will help to be easy support manjaro and arch at the same time. If someone will develop an app for arch and you want to port it to manjaro and manjaro has a different interface in some library, you will need to patch this application, what i talk is about reduce to the minimum this inconvenient. I don't say that anything is wrong. About help, well, i don't consider will be helpful use my first lines of code in vala. First i need to learn. Sorry.

**Comment by angiest** [comment]
I believe I have a similar problem with pamac (Manjaro, Arch, Antergos).  

My proxy at work seems to be doing .... something, that causes curl to fail with similar (example taken from the pacman command):

core                     121.8 KiB  29.7M/s 00:00 [######################] 100%
error: failed retrieving file 'extra.db' from mirror.rit.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

If I modify pacman.conf to use wget, it does complete successfully. Is there a reason why the setting in pacman.conf is not being honored by pamac?

**Comment by guinux** [comment]
I tried to fix this issue in v3.0.0, tell me if it's works.

**Comment by jetm** [comment]
@guinux: pamac through a proxy is working for me. Thanks!

**Comment by angiest** [comment]
I continue seeing this on 3.0:

Error: community.db: failed retrieving file 'community.db' from lug.mtu.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

Just about any mirror.  This seems to be due to my work firewall/proxy as everything works perfectly at home.

For pacman and octopi I am using wget and it works.

**Comment by guinux** [comment]
Please try again with v3.1.0

**Comment by angiest** [comment]
The update hasn't hit repos or the AUR yet.  I'll test it once it is
available.

On Mon, Feb 22, 2016 at 7:05 AM, guinux <notifications@github.com> wrote:

> Please try again with v3.1.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manjaro/pamac/issues/2#issuecomment-187162454>.
>



-- 

We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time.
    - TS Eliot, "Little Gidding," from "Four Quartets"

**Comment by guinux** [comment]
It's fixed in v4
