### ISSUE TITLE
Pamac ignores nobuildconfirm option.

### ISSUE THREAD

**Issue by 8BitSloth** [manjaro/pamac#229]
After the recent Pamac update, the program totally ignores disabling nobuildconfirm in the config file. I want and need the ability to edit certain PKGBUILD files and, what I assume is a bug, has totally taken this ability away from me. If this is by choice, it is a bad choice. Keep nobuildcofirm enabled as the default option, add the ability to disable it back into the Pamac settings/config file, and stop removing a useful options, please.

**Comment by philmmanjaro** [comment]
**pamac** uses it's own native **AUR** support. For now we don't support editing **PKGBUILD**s.

**Comment by polarathene** [comment]
Can we have the ability to use the previous AUR support before native pamac support? I've been waiting weeks to be able to update some AUR packages that refuse to update because they have a dependency on an older version of openSSL, Arch still hasn't pushed it to stable, yet Manjaro's decision to do so is now preventing me from updating my software.

**Comment by polarathene** [comment]
Ran into another issue with an AUR package update where a dependency has been renamed and the maintainer has not updated it for months(git package). Requires to edit the PKGBUILD to fix, with prior AUR support this was possible, I'd like to do it via Pamac again.

Is there any discussion/details on what's required to get this support available once more in Pamac? If it's not difficult perhaps I can contribute or collaborate on it?

**Comment by polarathene** [comment]
@guinux  Any reason this was closed? Did it get resolved in a new release?

**Comment by guinux** [comment]
This option was a yaourt one. Now pamac uses it's own native AUR support, with automatic build.

**Comment by polarathene** [comment]
I don't get why this is being marked as not a bug and closed. It requests ability to edit PKGBUILD instead of automatic build. I gave some examples above where automatic build fails because PKGBUILD is broken, I have to use Octopi or CLI instead of Pamac when this happens.

Shouldn't the issue remain open until the feature is supported by Pamac? Or will Pamac never allow editing PKGBUILD? I believe this is important feature to support, it is not uncommon for me with the amount of AUR packages I use to run into PKGBUILD problems.

**Comment by guinux** [comment]
Because the title is talking about nobuildconfirm option.
Use #87 for viewing/editing PKGBUILD request.
