### ISSUE TITLE
I can't rank the mirrors by country.

### ISSUE THREAD

**Issue by kouros17** [manjaro/pamac#230]
After the last update of **pacman-mirrors** to **4.0.0-1** (unstable branch and **pamac 4.3.2-1**) I can't choose from preferences (official repositories" tab) the country which I want to rank the mirrors, I have only the "worldwide" option. 

![pamac](https://cloud.githubusercontent.com/assets/26252554/24091164/fab9dc70-0d4e-11e7-8a34-aba6f51f66b2.jpg)

**Comment by philmmanjaro** [comment]
Mirror-Ranking changed. **pacman-mirrors v4.0** uses a different routine. **Pamac** needs adopt to it to have it function again.

**Comment by guinux** [comment]
Can someone tell me where to find now the countries names with this new pacman-mirrors ?

**Comment by philmmanjaro** [comment]
@guinux: we are using now a [json format](https://github.com/manjaro/manjaro-web-repo/blob/master/mirrors.json). You can ask @Huluti and @fhdk for more info about the changes made to **pacman-mirrors**.

**Comment by fhdk** [comment]
@guinux 
The files are located in `/var/lib/pacman-mirrors/{mirrors,status,custom-mirrors}.json`.
A fallback mirrors.json is located at `/usr/share/pacman-mirrors/mirrors.json`.
The first two are downloaded at every run sufficed an internet connection is available.
The files are used by pacman-mirrors as follows

`OnlyCountry = Custom` is using custom-mirrors.json

Otherwise it is

* `/var/lib/pacman-mirrors/status.json` and if not exist
* `/var/lib/pacman-mirrors/mirrors.json` and if not exist
* `/usr/share/pacman-mirrors/mirrors.json` as fallback

If you want a list of countrynames do

    pacman-mirrors -l

**Comment by guinux** [comment]
Thanks, it's fixed now :)

**Comment by philmmanjaro** [comment]
Check if **v4.3.3-2** works for you ...
