### ISSUE TITLE
Partial updates

### ISSUE THREAD

**Issue by erikdubois** [manjaro/pamac#248]
"The pamac front end runs partial upgrades by default  and these are specifically warned against by the Arch Linux developers." to quote a forum post.

Is it true that pamac performs partial upgrades? like said here
[link](https://forums.bunsenlabs.org/viewtopic.php?pid=50239#p50239)

Can it pose a risk to the users and cause instability and broken packages?

**Comment by philmmanjaro** [comment]
No, we do always full updates. You can use the **updater** and deselect packages if you like. Those will be then blacklisted. You can remove blacklisted packages in settings to be updated regular once again. However we always recommend to not uncheck any package within an update.

**Comment by erikdubois** [comment]
thanks for your quick reply
closing

**Comment by AladW** [comment]
`start_refresh` runs the equivalent of `pacman -Sy` whenever it is run, which is done [frequently even without user interaction](https://github.com/manjaro/pamac/search?utf8=%E2%9C%93&q=start_refresh&type=). As such whenever you install a package, for example through the command line, you're in for a [partial upgrade](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported). 

Not so much an issue in Manjaro (which I guess is the intended target of the software), but in Arch where updates are pushed continuously to the repos the consequences may be severe. For example, when openssl 1.1 was pushed there were all kinds of issues for users who did partial upgrades, breaking `pacman`.

A simple solution is implemented by [checkupdates](https://git.archlinux.org/pacman-contrib.git/tree/src/checkupdates.sh.in) which uses a database in a temporary directory, then prints candidate updates.

**Comment by Tomaszal** [comment]
In my opinion this issue shouldn't be quickly dismissed, as this is a major (maybe even the biggest) shortcoming in `pamac`.

Of course the primary goal of it is to be used on a Manjaro distribution, for which this isn't so important. But with it being available on Arch's user repositories and being quite popular there, it would be great if it worked on 'pure' Arch as well as it does on Manjaro. That is without a high risk of it messing up the system without user interaction.

It would be great for the community if this issue was fixed, as currently there is no good alternative to `pamac` that doesn't have this problem or isn't missing several important features. And if ends up not being fixed, I think there should at least be a warning on non-Manjaro distributions about the possible consequences.

**Comment by guinux** [comment]
I understand, I will fix it in the next release.
I also wanted pamac to works well in Arch.

**Comment by guinux** [comment]
Fixed in v5.0.0
