### ISSUE TITLE
Pamac doesn't show updates

### ISSUE THREAD

**Issue by ShabazzKing** [manjaro/pamac#423]
Icon in tray shows, that there are updates, but only one update - waterfox from AUR. Other updates (from repository) are omitted by Pamac. Despite that Pamac performs full update, but doesn't show those updates before operation begins.

**Comment by IevgenSobko** [comment]
Having the same issue in Antergos KDE installation.
Pamac shows no update even you run refresh repos from ui.
But after running `sudo pacman -Syu` it starting to see updates.

**Comment by P3p1t0** [comment]
I got the exact same issue with Pamac 6.2.5-2. Pamac never showed updates published with [Testing 2018-03-31](https://forum.manjaro.org/t/testing-update-2018-03-31-kernels-udisks2-spl-zfs-pamac/43766) update release despite the fact that the mirror I use was perfectly up to date (I tried to refresh my mirror list with pacman-mirrors, but it didn't work).

As soon as I use pacman -Syu, updates were detected. I still updated my system with pacman though.

I think this issue is what this commit is supposed to solve. The fix is included in Pamac 6.2.7.
https://github.com/manjaro/pamac/commit/4c68ccb8838ea928681afcb5aa14fb94df691ae5

**Comment by P3p1t0** [comment]
> Seems it started to work for me even without upgrading to 6.2.7.

According to Antergos' Github, Antergos published a new package of Pamac 6.2.6 patched with more commits on March 30, 2018.

https://github.com/Antergos/antergos-packages/commit/2de3f238939d1b3f6642d29f550204f11fb16201

My guess is that when you updated your system with pacman -Syu, you got a new package for Pamac 6.2.6, a package that ships Pamac 6.2.6 with a few more commits on it, which is why it works correctly without actually having Pamac 6.2.7.
