### ISSUE TITLE
PAMAC does not copy PLASMA decorations

### ISSUE THREAD

**Issue by W54J04S07T** [manjaro/pamac#444]
Specifically in KDE/Plasma PAMAC does not assume the appearance of other apps relative to the current decoration.  This appears to be an intentional design decision as it doesn't match the decoration in any other DE I've used.  Wonder if matching the decoration could at least be an option?

More importantly, the borders are lost and you cannot resize PAMAC.  This seems to be KDE/Plasma specific to "real" machines.  The problem does not manifest in VMs or other DEs( e.g. -- OpenBox ).
Ideas?

**Comment by seafox** [comment]
I can confirm that behaviour on Arch Plasma also. Indeed that must be a bug, as pamac main window maximizing has the expected effect of enlarging its size and there is no reasons to avoid the expected behaviour.

**Comment by guinux** [comment]
It's a theme issue. You use a gtk3 theme with doesn't not support resize gtk3 window using CSD in plasma.
It affects all gtk3 app using CSD in plasma even Firefox with CSD.
See that if you changed gtk3 theme with one supporting CSD (Adwaita or any real gtk theme) in system settings the problem gone.

**Comment by seafox** [comment]
I don't think FF have that problem (see FF window can be resized):
![image](https://user-images.githubusercontent.com/9025690/40872649-59e4a512-6641-11e8-895c-550662515c4c.png)

![image](https://user-images.githubusercontent.com/9025690/40872728-b7f84a68-6642-11e8-9743-c2bf981d1030.png)

**Comment by guinux** [comment]
It's because you don't use CSD with firefox, go to "Customize" in the menu and unselect "Title Bar" at the bottom.

**Comment by seafox** [comment]
Nope, you don't have to explain the behaviour by FF customization options, as other apps also do obey the expected behaviour like titlebar color change in background/foreground or minimizing on tray on second click.

![image](https://user-images.githubusercontent.com/9025690/40873187-46487ab0-664b-11e8-9f6b-c23481a03d7e.png)

**Comment by philmmanjaro** [comment]
@seafox: I don't get your issue here. Pamac uses CSD. In FF you may enable or disable that feature. In Pamac you can't. It works perfectly fine in XFCE, Gnome and other DEs. KDE should be also fine. You may try **gtk3-mushrooms** or **gtk3-classic** packages to have the old behaviour.

**Comment by philmmanjaro** [comment]
@seafox: with **Pamac** we focus on **Gnome** and NOT **KDE**. Therefore we comply with CSD and its design philosophies. I already provided you a solution by installing other gtk3 packages. Another would be to use [pamac-classic](https://github.com/cromnix/pamac-classic). Please use [our PKGBUILD](https://github.com/manjaro/packages-community/tree/master/pamac-classic).

**Comment by philmmanjaro** [comment]
See also here: https://github.com/manjaro/pamac/issues/410

**Comment by seafox** [comment]
@philmmanjaro 
The emphasized here UI issues with pamac aren't what you would normally face in KDE. Not in FF, not in any other gtk app I've installed. So it would be a reasonable expectation to have at least an option (and preferably by Default!) for pamac to behave the way other apps do.
Re pamac-classic, looks like the its future set lags behind aur-git version, or is it synced properly?

**Comment by philmmanjaro** [comment]
Well, by default we use CSD as only option. However we respect `GTK_CSD=0`. You may try to use either **gtk3-classic** ([manjaro](https://github.com/manjaro/packages-extra/tree/master/gtk3-classic)) or **gtk3-mushrooms** ([aur](https://aur.archlinux.org/packages/gtk3-mushrooms)), which disables CSD by default. And please stop complaining about our design decisions we do for **Pamac**.

**[pamac-classic](https://github.com/cromnix/pamac-classic)** is a different project, not supported and developed by the Manjaro community. Please check with the author of it for more information.

**Pamac with GTK3**

![pamac-csd](https://user-images.githubusercontent.com/5050022/40873664-707ae4fe-6654-11e8-91ff-f382d0bd8892.jpg)

**Pamac with GTK3** (Classic/Mushrooms)

![pamac-no-csd](https://user-images.githubusercontent.com/5050022/40873667-805c6384-6654-11e8-8246-3370b8e540d6.jpg)

**Comment by seafox** [comment]
> And please stop complaining about our design decisions we do for Pamac.

@philmmanjaro 
Please find the difference between complaining and criticizing with rationale.
Providing you are still want bug reports and discussion to improve your product, of course )

@philmmanjaro, @guinux 
1. Just tried the gtk3 >> gtk3-mushrooms. No, it does not improve. Reasons:
Provided Breeze is chosen as the theme for consistency (apparently the theme you provided in pics above has the same behaviour), that makes windows captions almost twice bigger in height, which is ugly and wastle of vertical space. Besides, as the title bar now obeys window fore/back-ground position, the lower bar with search and menu icons on the right still has the same (black color). The fix one would expect is the merged two-in-one bars in pair with reflecting the back/fore-ground main app window position.
![image](https://user-images.githubusercontent.com/9025690/40874604-afd3b020-6660-11e8-8f85-7a3a827f3384.png)
2. This musrooms didn't fixed mentioned here bug with second click on tray icon that should minimize pamac to tray. It's possibly just event handling omission in pamac rather than themes or gtk issue.

**Comment by seafox** [comment]
> See also here: #410

Nope, tried "the hack package" gtk3-nocsd-git with lib32 part from AUR without env var, and with GTK_CSD=0, GTK_CSD=1, no effect. on pamac-aur-git. Still shows double title bar. BTW #410 was closed without any clue whether fix was applied or not. Moreover it even couldn't be uninstalled cleanly. Sorry!

**Comment by seafox** [comment]
@guinux 

> As I said it's a theme issue with all gtk3 apps using CSD. If you change gtk3 theme it fixes the issue. The problem is with breeze-gtk3 theme.

Nope, with Arch Plasma Breeze gtk3 theme has black title bar, Default and Emacs - gray. But all 3 do not change the color when passed in background.

**Comment by philmmanjaro** [comment]
@seafox: I still don't get your issue here. If you use **gtk3-mushrooms** it will disable CSD and displays the headerbar as you wanted and our menu in two separate bars. With CSD enabled, those get merged to one bar, however the gtk3-breeze theme won't handle that yet properly. Did you tried some like Adwaita yet? 

To answer some of your other questions:

#410 was closed via https://github.com/manjaro/pamac/commit/6ea47099db5a174e7bc57a2e1d42268ab74c9f60, which was mentioned in the issue. #216 got closed as it got implemented in **v6.4.0**, to download updates automatically in the background. However, **Pamac** will always depend on **Pacman**, which ships the **alpm-libs**. And remember, we are coding for Gnome and NOT for KDE! There we recommend to use **[Octopi](https://github.com/aarnt/octopi)**.

---

Pamac-Classic also uses CSD. So it won't make much difference on your end. Therefore we recommend to change the GTK3-Theme on your end to something other than Breeze-GTK3.
**Pamac-Classic** (CSD)

![pamac-cl-csd](https://user-images.githubusercontent.com/5050022/40879443-6be9e526-668f-11e8-8948-a14a5e69d904.jpg)

**Pamac-Classic** (No CSD)

![pamac-cl-no-csd](https://user-images.githubusercontent.com/5050022/40879449-766203a8-668f-11e8-8def-7a3e3b97bc52.jpg)

**Comment by seafox** [comment]
#444 I don't want to see two stacked title bars with different visual look, so I guess no disabled CSD for me. What I do wish to see is the default KDE behaviour as described here (single title bar with common selected style, its proper color change in back/foreground, working window resizing), that will not come by trying 4 built-in Arch gtk3 themes. _It's plain wrong_ and I do not wish to install something else _to hack a look of single pamac app_ just for the sake of consistency! Try something like ... is rather vague advice.
#410 Tried and found no diff - always two stacked bars, irrespectively of env var. See above.
#216 You are clearly ignoring my question, so I'll try to repeat it here the 3rd last time:
**Currently when Manjaro keeps the winner's place in distrowatch, do you guys have plans to implement a system update daemon with transactional atomic updating mechanism, and get rid of pamac modal confirmation-only dialogs in favor of system notification messages aiming to achieve a seemless in-background updating process?**
_What obvious intention stands behind to not distinguishing between in #216 proposed essentials of (semi-)automatic updates and your already implemented but only the first step to that (i.e. the automatic download in background)?_ **These are completely different things to close the issue like that!**
As to Octopi suggestion for KDE. If you want to develop one app for 2 of 3 official DEs and point users to another that has different look and features, instead of having a single app that works in all DEs and also does obey their respective minimal requirements for look and feel then you're taking consious risk of losing your efforts on pamac... I personally do not depend on pamac, Octopi or Manjaro and I'm okay with pacaur or similar tool that can be easily automated to bring better UX than your autodowload step named "(semi)automatic updates" :)

**Comment by philmmanjaro** [comment]
@seafox: seems we are driving in a loop here. All answers we wanted to answer we answered. The issue you have is with the **breeze-gtk3** theme, which is known. It also happens to **firefox** and other applications using **CSD**. The solution we already posted. Switch to [**Adwaita** theme](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Adwaita), which is the default one for Gnome. And again, our focus for **Pamac** is not to support KDE.
